# preload = ~/.config/hypr/wallpapers/pokemon4.jpg
# wallpaper = , ~/.config/hypr/wallpapers/pokemon4.jpg

preload = /home/tyler/.config/hypr/wallpapers/pokemon1.jpg

wallpaper {
    monitor = DP-3
    path = /home/tyler/.config/hypr/wallpapers/pokemon1.jpg
    fit_mode = cover
}